package inc.generics.presentation.theme.localization.localized_strings

import inc.generics.presentation.theme.localization.StringsKeys.*

internal val englishStrings = hashMapOf(
    Pair(DUET, "Duet"),
    Pair(YES, "Yes"),
    Pair(NO, "No"),
    Pair(AUTH_BY_VK, "Login via VK"),
    Pair(AUTH_TEXT, "Login or register.\n" +
            "Use any of the suggested\n" +
            "Below is the login method"),
    Pair(CREATE_GROUP, "Group creation"),
    Pair(CREATE, "Create"),
    Pair(INPUT_NAME_GROUP, "Enter group name"),
    Pair(NO_MORE, "*no more than %d characters\n*and no less than %d characters"),
    Pair(DIALOG_ERROR_TITLE, "Something went wrong..."),
    Pair(OK_ON_ERROR, "Got it:("),
    Pair(OK, "Ok"),
    Pair(CHECK_INTERNET_OR_FILE, "Check your internet connection or upload another file"),
    Pair(CHECK_INTERNET_OR_TRY_AGAIN, "Check your internet connection or try again later"),
    Pair(ERROR_NAME_GROUP, "Group name is a required field.\n" +
            "Enter the group name"),
    Pair(NO_ACTIVE_GROUP, "You don't have\n" +
            "an active group"),
    Pair(INTO_TO_GROUP, "Join"),
    Pair(BASKET, "Basket"),
    Pair(TITLE_REQUEST_DIALOG, "Are you sure?"),

    Pair(NEW_CODE, "New inviteCode"),
    Pair(SAVE_ARCHIVE, "Download archive"),
    Pair(PARTNER_LEAVE, "Your partner \n" +
            "dropped out"),
    Pair(GET_OUT, "Get out"),
    Pair(PARTNER_DELETE_GROUP, "Your partner \n" +
            "has placed the group\n" +
            "in the basket"),
    Pair(REQUEST_DELETE_GROUP, "Are you sure you want to send the group to the basket?"),
    Pair(REQUEST_DELETE_PARTNER, "Are you sure you want to remove a partner from the group?"),
    Pair(DELETE_PARTNER, "Delete partner"),

    Pair(REQUESTS, "Requests"),
    Pair(ACCEPT, "Accept"),
    Pair(CANCEL, "Cancel"),
    Pair(SWIPE_REFRESH_REQUESTS, "Pull the screen down to\nrefresh the list"),
    Pair(EMPTY_LIST, "List is empty"),

    Pair(CODE_IS_COPIED, "Code is copied"),
    Pair(CLICK_TO_COPY_CODE, "click to copy code"),
    Pair(EDIT, "Edit"),

    Pair(JOIN_TO_GROUP, "Group request"),
    Pair(INPUT_INVITE_CODE, "Enter the invitation code"),
    Pair(INPUT_INVITE_CODE_TEXT, "Enter the invitation code that\ngenerated by the partner"),
    Pair(SEND, "Send"),
    Pair(EMPTY_INPUT_FIELD_INVITE_CODE, "Empty input field. Insert the invitation code"),
    Pair(CHECK_INVITE_CODE_OR_TRY_AGAIN, "Check if the invitation code is correct or try again later"),
    Pair(REQUEST_TO_JOIN_IS_SENT_WAIT, "Application has been sent.\n" +
            "Wait for the\n" +
            "partner accepts it"),

)