package inc.generics.presentation.theme.localization

enum class StringsKeys {
    DUET,
    YES,
    NO,
    AUTH_BY_VK,
    AUTH_TEXT,
    CREATE_GROUP,
    CREATE,
    INPUT_NAME_GROUP,
    NO_MORE,
    DIALOG_ERROR_TITLE,
    OK_ON_ERROR,
    OK,
    CHECK_INTERNET_OR_FILE,
    CHECK_INTERNET_OR_TRY_AGAIN,
    ERROR_NAME_GROUP,
    NO_ACTIVE_GROUP,
    INTO_TO_GROUP,
    BASKET,

    TITLE_REQUEST_DIALOG,
    NEW_CODE,
    SAVE_ARCHIVE,
    PARTNER_DELETE_GROUP,
    GET_OUT,
    PARTNER_LEAVE,
    REQUEST_DELETE_GROUP,

    REQUESTS,
    ACCEPT,
    CANCEL,
    SWIPE_REFRESH_REQUESTS,
    EMPTY_LIST,

    CODE_IS_COPIED,
    CLICK_TO_COPY_CODE,
    EDIT,

    JOIN_TO_GROUP,
    INPUT_INVITE_CODE,
    INPUT_INVITE_CODE_TEXT,
    SEND,
    EMPTY_INPUT_FIELD_INVITE_CODE,
    CHECK_INVITE_CODE_OR_TRY_AGAIN,
    REQUEST_TO_JOIN_IS_SENT_WAIT,

    DELETE_PARTNER,
    REQUEST_DELETE_PARTNER,

    PROFILE,
    NO_ACTIVE_GROUP_ONE_LINE,
    NO_PARTNER,
    SETTINGS,
    LANGUAGE,
    COLOR_THEME,
    REQUEST_TO_LOGOUT
}